version: 2
updates:
- package-ecosystem: docker
  directories:
  - /variants/*
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directories:
  - /
  schedule:
    interval: daily
