rules:
  anchors:
    forbid-duplicated-anchors: true
    forbid-unused-anchors: true
  braces: &brackets
    forbid: non-empty
  brackets: *brackets
  colons: enable
  comments: enable
  comments-indentation: enable
  document-end: &document
    present: false
  document-start: *document
  empty-lines:
    max: 1
  empty-values: enable
  float-values:
    require-numeral-before-decimal: true
  hyphens: enable
  indentation:
    spaces: 2
    indent-sequences: false
  key-duplicates:
    forbid-duplicated-merge-keys: true
  line-length:
    allow-non-breakable-words: false
  new-line-at-end-of-file: enable
  new-lines: enable
  octal-values:
    forbid-explicit-octal: false
  quoted-strings:
    quote-type: double
    required: only-when-needed
    check-keys: true
  trailing-spaces: enable
  truthy: enable
