name: CI
# run-name: test-run-name-variants
on:  # yamllint disable-line rule:truthy
  pull_request: {}
  push: {}
  # schedule:
  # - cron: 0 1 * * *
  # workflow_dispatch: {}
permissions:
  actions: read
  contents: read
  security-events: write
jobs:
  pre-commit:
    name: Ensure pre-commit passes
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - name: Run pre-commit
      uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1
  actions-sha:
    name: Ensure SHA pinned actions
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - name: Ensure SHA pinned actions
      uses:
        # yamllint disable-line rule:line-length
        zgosalvez/github-actions-ensure-sha-pinned-actions@5d6ac37a4cef8b8df67f482a8e384987766f0213  # v3.0.17
  list-variants:
    name: List variants
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    outputs:
      variants: ${{ steps.list-variants.outputs.variants }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - id: get-changed-files
      name: Get changed files
      uses:
        # yamllint disable-line rule:line-length
        tj-actions/changed-files@4edd678ac3f81e2dc578756871e4d00c19191daf  # v45.0.4
      with:
        dir_names: true
        dir_names_exclude_current_dir: true
        dir_names_max_depth: "1"
        matrix: true
        path: variants
    - id: list-variants
      name: List variants
      run: |
        ./scripts/list_variants.sh
        variants_json=$(jq -c '.' output/variants.json)
        printf "variants=%s\n" "${variants_json}" >>"${GITHUB_OUTPUT:?}"
      env:
        FILTER_VARIANTS: >-
          ${{
            contains(fromJSON('["pull_request", "push"]'), github.event_name)
            && steps.get-changed-files.outputs.all_changed_and_modified_files
          }}
    - name: Upload variants to artifacts
      uses:
        # yamllint disable-line rule:line-length
        actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882  # v4.4.3
      with:
        name: variants
        path: output
        if-no-files-found: error
  variants:
    name: Variants
    permissions:
      actions: read
      contents: read
      security-events: write
    needs: list-variants
    if: ${{ needs.list-variants.outputs.variants != '[]' }}
    uses: ./.github/workflows/ci-variant.yaml
    with:
      name: ${{ matrix.variant.name }}
      filter-tags: ${{ matrix.variant.config.filter-tags }}
    strategy:
      matrix:
        variant: ${{ fromJSON(needs.list-variants.outputs.variants) }}
      fail-fast: false
